### ISSUE TITLE
oom when update_policy

### ISSUE THREAD

**Issue by zjhthu** [rllm-org/rllm#30]
When I was training, I encountered an OOM (Out Of Memory) error in the `update_policy` function. I tried the following adjustments:

- `actor_rollout_ref.actor.ppo_micro_batch_size = 1`
- `actor_rollout_ref.rollout.gpu_memory_utilization = 0.3`
- `data.max_response_length = 4096`

However, I'm still experiencing OOM issues. My machine has 8 A100 40G GPUs. Could you please provide any suggestions?

**Comment by michaelzhiluo** [comment]
Looking like you are OOMing during actor update; You might want to increase sequence parallelism... This will distribute the activations of the KV blocks across GPUs.

**Comment by zjhthu** [comment]
Are you suggesting to increase `actor_rollout_ref.actor.ulysses_sequence_parallel_size`? I tried setting it to 2 or 4, but it still seems to run OOM. This time it crashed on `old_log_prob = self.actor_rollout_wg.compute_log_prob(batch)`. The error message is:

```
SYSTEM_ERROR Worker exit detail: Worker unexpectedly exits with a connection error code 2. End of file. There are some potential root causes. 
(1) The process is killed by SIGKILL by OOM killer due to high memory usage. 
(2) ray stop --force is called. 
(3) The worker is crashed unexpectedly due to SIGSEGV or other unexpected errors.
```

It appears that it might still be due to OOM.

Currently, my complete config settings are as follows:

```bash
python3 -m verl.trainer.main_ppo \
    algorithm.adv_estimator=grpo \
    data.train_files=$HOME/deepscaler/data/train.parquet \
    data.val_files=$HOME/deepscaler/data/aime.parquet \
    data.train_batch_size=128 \
    data.val_batch_size=512 \
    data.max_prompt_length=1024 \
    data.max_response_length=8192 \
    actor_rollout_ref.model.path=$MODEL_PATH  \
    [actor_rollout_ref.actor.optim.lr](http://actor_rollout_ref.actor.optim.lr/)=1e-6 \
    actor_rollout_ref.model.use_remove_padding=True \
    actor_rollout_ref.actor.ppo_mini_batch_size=64 \
    actor_rollout_ref.actor.ppo_micro_batch_size=1 \
    actor_rollout_ref.actor.use_dynamic_bsz=True \
    actor_rollout_ref.actor.ppo_max_token_len_per_gpu=32768 \
    actor_rollout_ref.actor.use_kl_loss=True \
    actor_rollout_ref.actor.kl_loss_coef=0.001 \
    actor_rollout_ref.actor.kl_loss_type=low_var_kl \
    actor_rollout_ref.actor.ulysses_sequence_parallel_size=4 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.actor.fsdp_config.param_offload=False \
    actor_rollout_ref.actor.fsdp_config.grad_offload=False \
    actor_rollout_ref.actor.fsdp_config.optimizer_offload=False \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.name=vllm \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.val_temperature=0.6 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.5 \
    actor_rollout_ref.rollout.n=8 \
    actor_rollout_ref.rollout.n_val=8 \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.critic_warmup=0 \
    trainer.logger=['console','wandb'] \
    trainer.project_name='deepscaler' \
    trainer.experiment_name='deepscaler-1.5b-8k' \
    +trainer.val_before_train=False \
    trainer.n_gpus_per_node=8 \
    trainer.nnodes=1 \
    trainer.save_freq=20 \
    trainer.test_freq=20 \
    trainer.default_hdfs_dir=null \
    trainer.total_epochs=30 "${@:1}"
```

Could you please provide any suggestions?

**Comment by michaelzhiluo** [comment]
Another possibility is that the Ray worker group is not properly swapping between sampler and actor for ActorRolloutRefWorker. Which means that the KV cache is still there (has not been swapped out) while the program is beginning to compute log probs.

**Comment by zjhthu** [comment]
ray version is '2.42.1'

**Comment by zjhthu** [comment]
Below is the complete information from the terminal output, as well as the version information for all Python libraries.
[log.txt](https://github.com/user-attachments/files/18813703/log.txt)

[version.txt](https://github.com/user-attachments/files/18813705/version.txt)

**Comment by michaelzhiluo** [comment]
The error you're getting:
```

(WorkerDict pid=1425649) [rank3]:[E216 12:40:54.571272158 ProcessGroupNCCL.cpp:607] [Rank 3] Watchdog caught collective operation timeo
ut: WorkNCCL(SeqNum=10, OpType=ALLTOALL, NumelIn=4031488, NumelOut=4031488, Timeout(ms)=600000) ran for 600042 milliseconds before timi
ng out.
(WorkerDict pid=1425649) [rank3]:[E216 12:40:54.571372033 ProcessGroupNCCL.cpp:1664] [PG 5 Rank 3] Exception (either an error or timeou
t) detected by watchdog at work: 10, last enqueued NCCL work: 11, last completed NCCL work: 9.
(WorkerDict pid=1425649) [rank3]:[E216 12:40:54.571386343 ProcessGroupNCCL.cpp:1709] [PG 5 Rank 3] Timeout at NCCL work: 10, last enque
ued NCCL work: 11, last completed NCCL work: 9.
(WorkerDict pid=1425649) [rank3]:[E216 12:40:54.571396826 ProcessGroupNCCL.cpp:621] [Rank 3] Some NCCL operations have failed or timed
out. Due to the asynchronous nature of CUDA kernels, subsequent GPU operations might run on corrupted/incomplete data.
(WorkerDict pid=1425649) [rank3]:[E216 12:40:54.571405547 ProcessGroupNCCL.cpp:627] [Rank 3] To avoid data inconsistency, we are taking
 the entire process down.
(WorkerDict pid=1425649) [rank3]:[E216 12:40:54.572732094 ProcessGroupNCCL.cpp:1515] [PG 5 Rank 3] Process group watchdog thread termin
ated with exception: [Rank 3] Watchdog caught collective operation timeout: WorkNCCL(SeqNum=10, OpType=ALLTOALL, NumelIn=4031488, Numel
Out=4031488, Timeout(ms)=600000) ran for 600042 milliseconds before timing out.
(WorkerDict pid=1425649) Exception raised from checkTimeout at ../torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp:609 (most recent cal
l first):
```

Usually comes from an FSDP worker crashing, I don't see OOM errors. Its most likely CUDA illegal memory access?

**Comment by zjhthu** [comment]
This issue appears to be caused by setting `actor_rollout_ref.actor.ulysses_sequence_parallel_size = 4`. When I reset it to 1, the worker does not crash; instead, it reports an OOM error. Below is the complete log.

[log_sp.txt](https://github.com/user-attachments/files/18813792/log_sp.txt)

Furthermore, when `ulysses_sequence_parallel_size = 1`, it runs further and oom at the `update_policy` stage.

**Comment by michaelzhiluo** [comment]
Remove checkpoints? Usually when the world size is different this can result in OOM

**Comment by zjhthu** [comment]
What does "Remove Checkpoints" mean? Since I have never been able to get it running, the outputs folder is empty.

**Comment by sunlightsgy** [comment]
same problem with 8x40G A100.

**Comment by kaiyliu** [comment]
Mark same problem with 8x40G A100

**Comment by kaiyliu** [comment]
> Mark same problem with 8x40G A100. If you solve this problem, can you post the solution here?标记8x40G A100的相同问题。如果你解决了这个问题，你能在这里发布解决方案吗？

In fact, setting data.train_batch_size to 16 would be fine. But, based on the author's recommendations, that's not a good idea, because too small a batch might learn noise

**Comment by sunlightsgy** [comment]
> > Mark same problem with 8x40G A100. If you solve this problem, can you post the solution here?标记8x40G A100的相同问题。如果你解决了这个问题，你能在这里发布解决方案吗？
> 
> In fact, setting data.train_batch_size to 16 would be fine. But, based on the author's recommendations, that's not a good idea, because too small a batch might learn noise

Set training bs to 16 not work for me.

**Comment by zjhthu** [comment]
This does not solve my issue. It can run for a few steps, but then it crashes.
